export const ELEMENTS = {
  buttonRegister: '[data-cy="button-btn-enroll"]',
  inputFistName: '[data-cy="input-signup-personal-data-firstName"]',
  inputLastName: '[data-cy="input-signup-personal-data-lastName"]',
  inputBirthDate: '[data-cy="input-signup-personal-data-birthDate"]',
  inputCPF: '[data-cy="input-signup-personal-data-cpf"]',
  inputEmail: '[data-cy="input-signup-personal-data-email"]',
  inputConfirmEmail: '[data-cy="input-signup-personal-data-email-confirm"]',
  inputPassword: '[data-cy="input-signup-personal-data-password"]',
  inputConfirmPassword: '[data-cy="input-signup-personal-data-password-confirm"]',
  inputCep: '[data-cy="input-signup-address-cep"]',
  inputNumber: '[data-cy="input-signup-address-number"]',
  inputComplement: '[data-cy="input-signup-address-complement"]',
  inputCountry: '[data-cy="input-signup-address-country"]',
  inputState: '[data-cy="input-signup-address-state"]',
  inputCity: '[data-cy="input-signup-address-city"]',
  toastAlert: '.toasts-list > [role="alert"]',
  dropdownButtonProficiency: '[aria-controls="dropdown-button-1"]',
  checkBoxTerms: '[data-cy="input-signup-personal-data-lgpd"]',
  buttonLeveling: '.btn > Fazer Nivelamento',
  buttonContinue: '[data-cy^="button-signup_submit_button_"]',
  inputError: '.input-error',
  titleSuccess: 'Thank you for joining us!',
}